#pragma once

#define WEG_PAPAYA_HUE  21
#define WEG_PURPLE_HUE  198

#define WEG_PAPAYA_HS   WEG_PAPAYA_HUE, 255
#define WEG_PURPLE_HS   WEG_PURPLE_HUE, 255

#define WEG_PAPAYA_HSV  WEG_PAPAYA_HS, 255
#define WEG_PURPLE_HSV  WEG_PURPLE_HS, 255

#define WEG_RED_RGB     255, 0, 0
